---
- hosts: example 
  tasks:
 - name: General | Install required packages.
   action: apt pkg={{ item }} state=installed
   with_items:
     - apache2
 - name: Restart Apache
   action: service name=apache2 state=restarted
