---
- hosts: all
  user: grzegorz 
  sudo: True 
  tasks:
  - name: install apache2
    action: apt pkg=apache2 state=latest
    notify: start apache2
  handlers:
  - name: start apache2
    action: service name=apache2 state=started